services:
  - type: web
    name: scraper-manager
    runtime: node
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install && npm run build
    startCommand: npm start
    plan: free
